import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {runInNewContext} from 'node:vm';
import {normalize,domain,networkRules,stealthRules,sitePackRules,SITE_PACKS,matchesHost,PRESETS,AD_DOMAINS} from '../settings.js';
test('migration keeps existing disabled sites and global pause',()=>{const s=normalize({enabled:false,disabledHosts:['Example.COM']});assert.equal(s.enabled,false);assert.deepEqual(s.disabledHosts,['example.com']);assert.equal(s.ads,true);assert.equal(s.schema,3);assert.equal(s.stealth,true);assert.deepEqual(s.stealthOff,[]);});
test('settings stored by 0.2.0 migrate without losing data and accept version-2 backups',()=>{const old={schema:2,enabled:true,ads:true,regional:false,privacy:true,compat:true,detectors:false,cosmetic:true,badge:false,disabledHosts:['a.test'],compatOff:['b.test'],cosmeticOff:[],blockDomains:['c.test'],allowDomains:[]};const s=normalize(old);assert.equal(s.schema,3);for(const key of Object.keys(old).filter(k=>k!=='schema'))assert.deepEqual(s[key],old[key],key);assert.equal(s.stealth,true);assert.deepEqual(s.stealthOff,[]);});
test('input validation, IDN and subtree boundaries',()=>{assert.equal(domain('Exámple.com'),'xn--exmple-qta.com');assert.equal(matchesHost('sub.example.com',['example.com']),true);assert.equal(matchesHost('notexample.com',['example.com']),false);for(const value of ['https://a.com','a.com/path','*.a.com','a.com:443','a.com@b.com','-a.com'])assert.throws(()=>domain(value));assert.throws(()=>normalize({ads:'true'}));assert.throws(()=>normalize({disabledHosts:new Array(201).fill('a.com')}));assert.throws(()=>normalize({blockDomains:['a.com'],allowDomains:['a.com']}));});
test('pause and custom exceptions have deterministic precedence',()=>{const s=normalize({disabledHosts:['site.test'],blockDomains:['bad.test'],allowDomains:['good.test']});const r=networkRules(s);assert.equal(r[0].action.type,'allowAllRequests');assert.ok(r[0].priority>r.find(x=>x.id===3).priority);assert.ok(r.find(x=>x.id===3).priority>r.find(x=>x.id===4).priority);assert.deepEqual(networkRules({...s,enabled:false}),[]);assert.equal(PRESETS.companion.ads,false);});
test('packaged rules preserve allow exceptions and provenance hashes',async()=>{const metadata=JSON.parse(await readFile(new URL('../rules/metadata.json',import.meta.url)));for(const l of metadata.lists){const original=await readFile(new URL('../vendor/'+l.upstream+'.json',import.meta.url));assert.equal(createHash('sha256').update(original).digest('hex'),l.sha256);const rules=JSON.parse(await readFile(new URL('../rules/'+l.id+'.json',import.meta.url)));assert.equal(rules.length,l.count);assert.equal(new Set(rules.map(r=>r.id)).size,rules.length);assert.ok(rules.every(r=>['block','allow'].includes(r.action.type)));assert.equal(rules.filter(r=>r.action.type==='allow').length,JSON.parse(original).filter(r=>r.action.type==='allow').length);}});
test('camouflage redirects are gated, ordered below list exceptions and honor exclusions',()=>{
 const base=normalize({});const rules=networkRules(base);
 const redirects=rules.filter(r=>r.action.type==='redirect');
 assert.equal(redirects.filter(r=>r.id<100).length,9);
 assert.equal(new Set(rules.map(r=>r.id)).size,rules.length);
 assert.ok(redirects.every(r=>r.priority>10&&r.priority<30),'above list blocks (10), below list exceptions (30)');
 assert.ok(redirects.every(r=>r.action.redirect.extensionPath.startsWith('/stubs/')));
 for(const gate of [{stealth:false},{ads:false},{enabled:false}])assert.equal(networkRules(normalize({...gate})).filter(r=>r.action.type==='redirect'&&r.id<100).length,0,JSON.stringify(gate));
 assert.equal(stealthRules(normalize(PRESETS.companion)).length,0);
 const excluded=stealthRules(normalize({stealthOff:['x.test']}));
 assert.ok(excluded.every(r=>r.condition.excludedInitiatorDomains.includes('x.test')));
 assert.ok(stealthRules(base).every(r=>!('excludedInitiatorDomains' in r.condition)),'no empty arrays in DNR conditions');
 const paused=networkRules(normalize({disabledHosts:['p.test']}));
 assert.ok(paused.find(r=>r.id===2).priority>Math.max(...paused.filter(r=>r.action.type==='redirect').map(r=>r.priority)));
 assert.ok(AD_DOMAINS.every(d=>/^[a-z0-9.-]+$/.test(d)));
});
test('local ad frames have no active content and never redirect main-frame navigation',async()=>{
 const frame=stealthRules(normalize({})).find(r=>r.action.redirect.extensionPath==='/stubs/frame.html');
 assert.deepEqual(frame.condition.resourceTypes,['sub_frame']);
 assert.deepEqual(frame.condition.requestDomains,[...AD_DOMAINS]);
 const html=await readFile(new URL('../stubs/frame.html',import.meta.url),'utf8');
 assert.match(html,/default-src 'none'/);
 assert.match(html,/<body><\/body>/);
 assert.doesNotMatch(html,/<(?:script|img|iframe|link)\b/i);
});
test('GPT adapter executes queued callbacks, preserves an existing API and never uses the network',async()=>{
 const source=await readFile(new URL('../stubs/googletag.js',import.meta.url),'utf8');
 let calls=0,ready=0,errors=0;
 const network=()=>{calls++;throw Error('unexpected network');};
 const window={googletag:{cmd:[()=>{throw Error('callback failure');},()=>ready++]},fetch:network,navigator:{sendBeacon:network},XMLHttpRequest:network,Image:network};
 runInNewContext(source,{window,fetch:network,navigator:window.navigator,XMLHttpRequest:network,Image:network,console:{error:()=>errors++}});
 assert.equal(ready,1);assert.equal(errors,1);
 const api=window.googletag;
 const service=api.pubads(),slot=api.defineSlot('/local',[300,250],'slot').addService(service);
 assert.equal(service.getSlots()[0],slot);
 slot.setTargeting('test',['a','b']);const copy=slot.getTargeting('test');copy.push('c');assert.equal(slot.getTargeting('test').length,2);
 assert.equal(slot.getResponseInformation(),null);
 api.cmd.push(function(){assert.equal(this,window);ready++;});
 api.display('slot');service.refresh();api.destroySlots();
 assert.equal(service.getSlots().length,0);assert.equal(ready,2);assert.equal(calls,0);
 runInNewContext(source,{window,console});assert.equal(window.googletag,api);
});
test('every redirect target exists in the package and is web-accessible',async()=>{
 const {access}=await import('node:fs/promises');
 const manifest=JSON.parse(await readFile(new URL('../manifest.json',import.meta.url)));
 assert.ok(manifest.web_accessible_resources[0].resources.includes('stubs/*'));
 for(const r of stealthRules(normalize({})))await access(new URL('..'+r.action.redirect.extensionPath,import.meta.url));
});
test('site pack blocks rotating third parties only for its own site and respects pauses',()=>{
 const pack=SITE_PACKS[0];const rules=sitePackRules(normalize({}));
 const block=rules.find(r=>r.action.type==='block');
 assert.deepEqual(block.condition.initiatorDomains,[pack.host]);assert.equal(block.condition.domainType,'thirdParty');
 assert.ok(block.condition.excludedResourceTypes.includes('main_frame'));
 assert.ok(block.priority>10&&block.priority<20,'above list blocks, below camouflage stand-ins');
 assert.ok(['fonts.googleapis.com','discord.com'].every(h=>block.condition.excludedRequestDomains.some(d=>h===d||h.endsWith('.'+d))));
 assert.ok(rules.some(r=>r.action.type==='redirect'&&r.condition.urlFilter==='||steamverde.net/sys-analytics.js'));
 assert.equal(new Set(networkRules(normalize({disabledHosts:['x.test']})).map(r=>r.id)).size,networkRules(normalize({disabledHosts:['x.test']})).length);
 assert.equal(sitePackRules(normalize({disabledHosts:['steamverde.net']})).length,0);
 assert.equal(sitePackRules(normalize({ads:false})).length,0);
 assert.equal(sitePackRules(normalize({enabled:false})).length,0);
});
